# Set up

In [1]:
import pandas as pd
from IPython.display import display
import numpy as np
import warnings
import plotly.express as px
from eda_support_functions import *
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Suppress all warnings
warnings.filterwarnings("ignore")

In [2]:
movie_input = pd.read_csv(
    "/Users/iliasx/Documents/GitHub/box-office-prediction/data/processed_data/movie.csv"
)
genres = pd.read_csv(
    "/Users/iliasx/Documents/GitHub/box-office-prediction/data/processed_data/genre.csv"
)
keywords = pd.read_csv(
    "/Users/iliasx/Documents/GitHub/box-office-prediction/data/processed_data/keyword.csv"
)
production_companies = pd.read_csv(
    "/Users/iliasx/Documents/GitHub/box-office-prediction/data/processed_data/production.csv"
)

In [3]:
movie = movie_input[
    [
        "movie_id",
        "imdb_id",
        "year",
        "month",
        "release_date",
        "quarter",
        "original_title",
        "is_released__scope",
        "is_released__US",
        "days_from_us_release",
        "runtime",
        "revenue_usd_adj",
        "budget_usd_adj",
        "surplus",
        "ratio_adj",
        "roi",
        "is_first_released_in_cinemas",
        "is_first_released_in_cinemas_safe",
        "release_category",
        "ageCert",
    ]
]

In [4]:
movie.groupby("release_category").size()

release_category
Close streaming release           256
Far streaming release            7977
Not released in major markets    1813
Streaming release                2085
dtype: int64

# Basic Understanding of the Data

In [5]:
movie.head(10)

,movie_id,imdb_id,year,month,release_date,quarter,original_title,is_released__scope,is_released__US,days_from_us_release,runtime,revenue_usd_adj,budget_usd_adj,surplus,ratio_adj,roi,is_first_released_in_cinemas,is_first_released_in_cinemas_safe,release_category,ageCert
0,8681,tt0936501,2008,2,2008-02-18,1,Taken,True,True,-65.0,94,3.210161e+08,3.538060e+07,1.251274e+08,9.073223e+00,3.536611,False,False,Streaming release,PG13
1,24684,tt1174732,2009,10,2009-10-29,4,An Education,True,True,120.0,100,3.706476e+07,1.065208e+07,7.880303e+06,3.479580e+00,0.739790,True,True,Far streaming release,PG13
2,95023,tt0087300,1986,2,1986-02-21,1,The Frog Prince,True,True,23325.0,100,2.780128e+00,3.613279e+06,-3.613277e+06,7.694196e-07,-1.000000,True,True,Far streaming release,PG
3,24685,tt0380798,2004,10,2004-10-06,4,Vipère au poing,True,False,-1.0,100,1.144569e+07,1.340625e+07,-7.683406e+06,8.537577e-01,-0.573121,False,False,Streaming release,U
4,8688,tt0120832,1998,8,1998-08-07,3,Snake Eyes,True,True,8236.0,98,1.942081e+08,1.364616e+08,-3.935758e+07,1.423170e+00,-0.288415,True,True,Far streaming release,R
5,8689,tt0078935,1980,2,1980-02-07,1,Cannibal Holocaust,True,False,-1.0,96,7.395680e+06,3.697840e+05,3.328056e+06,2.000000e+01,9.000000,False,False,Streaming release,U
6,45077,tt1301990,2010,1,2010-01-14,1,Every Day,False,False,-1.0,93,6.431893e+04,4.192070e+06,-4.159910e+06,1.534300e-02,-0.992328,False,False,Not released in major markets,U
7,24686,tt1366687,2009,3,2009-03-05,1,Любовь в большом городе,True,True,14661.0,88,1.630786e+07,4.970970e+06,3.182958e+06,3.280619e+00,0.640309,True,True,Far streaming release,U
8,45094,tt1244754,2010,10,2010-10-15,4,Conviction,True,True,651.0,107,1.652651e+07,1.746696e+07,-9.203703e+06,9.461584e-01,-0.526921,True,True,Far streaming release,U
9,245775,tt2707858,2014,1,2014-01-08,1,Yves Saint Laurent,True,True,12974.0,106,2.706286e+07,1.544515e+07,-1.913725e+06,1.752191e+00,-0.123905,True,True,Far streaming release,R

In [6]:
null_percentage_all = movie.isnull().mean() * 100

zero_percentage_all = (movie == 0).mean() * 100

null_zero_percentage_all = pd.DataFrame(
    {"Null Percentage": null_percentage_all, "Zero Percentage": zero_percentage_all}
)
print(null_zero_percentage_all)

                                   Null Percentage  Zero Percentage
movie_id                                   0.00000         0.000000
imdb_id                                    0.02473         0.000000
year                                       0.00000         0.000000
month                                      0.00000         0.000000
release_date                               0.00000         0.000000
quarter                                    0.00000         0.000000
original_title                             0.00000         0.000000
is_released__scope                         0.00000        14.945182
is_released__US                            0.00000        30.145907
days_from_us_release                       0.00000         0.313247
runtime                                    0.00000         0.000000
revenue_usd_adj                            0.00000         0.000000
budget_usd_adj                             0.00000         0.000000
surplus                                    0.00000         0.197840
ratio_adj                                  0.00000         0.000000
roi                                        0.00000         0.197840
is_first_released_in_cinemas               0.00000        32.132553
is_first_released_in_cinemas_safe          0.00000        34.242849
release_category                           0.00000         0.000000
ageCert                                    0.00000         0.000000

In [7]:
movie[movie.budget_usd_adj != 0][
    ["revenue_usd_adj", "budget_usd_adj", "surplus", "ratio_adj", "roi"]
].describe(
    percentiles=[0.01, 0.05, 0.1, 0.25, 0.50, 0.75, 0.9, 0.95, 0.99, 0.999, 0.9999]
).drop("count").style.format(
    {
        "revenue_usd_adj": "${:,.0f}",
        "budget_usd_adj": "${:,.0f}",
        "surplus": "${:,.0f}",
        "ratio_adj": "{:.2f}",
        "roi": "{:.2f}",
    }
)

In [8]:
print("Smallest ratio movies")
display(
    movie.sort_values(by="ratio_adj")
    .head(10)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

print("Biggest ratio movies")
display(
    movie[movie.budget_usd_adj != 0]
    .sort_values(by="ratio_adj", ascending=False)
    .head(10)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

Smallest ratio movies

Biggest ratio movies

In [9]:
print("Movies with ratio_adj > more than 10 and less than 0.1")
display(
    movie[(movie.ratio_adj > 10) | (movie.ratio_adj < 0.1)][
        ["movie_id", "original_title", "revenue_usd_adj", "budget_usd_adj", "ratio_adj"]
    ]
)

Movies with ratio_adj > more than 10 and less than 0.1

,movie_id,original_title,revenue_usd_adj,budget_usd_adj,ratio_adj
2,95023,The Frog Prince,2.780128e+00,3.613279e+06,7.694196e-07
5,8689,Cannibal Holocaust,7.395680e+06,3.697840e+05,2.000000e+01
6,45077,Every Day,6.431893e+04,4.192070e+06,1.534300e-02
14,245846,Strangerland,1.428359e+05,1.285570e+07,1.111070e-02
18,549003,Marham,1.397357e+00,1.397357e+04,1.000000e-04
...,...,...,...,...,...
12110,94901,About Cherry,1.103512e+04,3.317835e+06,3.326000e-03
12117,24671,River Queen,1.428249e+06,3.749098e+07,3.809580e-02
12118,245692,The Search,5.598315e+05,3.217740e+07,1.739828e-02
12120,45061,Bus Palladium,3.507337e+02,1.201727e+07,2.918581e-05
12124,132342,Libertador,1.961963e+06,6.539876e+07,3.000000e-02

Example of outlier, indeed a wrong imdb data entry

https://www.imdb.com/title/tt1334328/


movie_id	original_title	revenue_usd_adj	budget_usd_adj	ratio_adj

53128	Ψυχή Βαθιά	2.903065e+06	4.092371	7.093847e+0

In [10]:
print("Smallest ROI movies")
display(
    movie.sort_values(by="roi")
    .head(15)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

print("Biggest ROI movies")
display(
    movie[movie.budget_usd_adj != 0]
    .sort_values(by="roi", ascending=False)
    .head(15)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

Smallest ROI movies

Biggest ROI movies

In [11]:
print("Smallest Surplus movies")
display(
    movie.sort_values(by="surplus")
    .head(10)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

print("Biggest Surplus movies")
display(
    movie[movie.budget_usd_adj != 0]
    .sort_values(by="surplus", ascending=False)
    .head(10)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

Smallest Surplus movies

Biggest Surplus movies

In [12]:
print("Basic statistics per is_released__US flag for the ratio and the ROI: ")
display(
    movie.groupby("is_released__US")[["ratio_adj", "roi"]]
    .describe()
    .style.format("{:,.2f}")
)

Basic statistics per is_released__US flag for the ratio and the ROI:

In [13]:
print("Basic statistics per release_category for the ratio:")
display(
    movie.groupby("release_category")[["ratio_adj"]].describe().style.format("{:,.2f}")
)

Basic statistics per release_category for the ratio:

In [14]:
print("Basic statistics per release_category for the ROI:")
display(movie.groupby("release_category")[["roi"]].describe().style.format("{:,.2f}"))

Basic statistics per release_category for the ROI:

In [15]:
print("Basic statistics per release_category for the ratio and the ROI: ")
display(
    movie.groupby(["release_category"])[["ratio_adj", "roi"]]
    .describe()
    .style.format("{:,.2f}")
)

Basic statistics per release_category for the ratio and the ROI:

In [16]:
movie[movie.original_title == "The Irishman"]

,movie_id,imdb_id,year,month,release_date,quarter,original_title,is_released__scope,is_released__US,days_from_us_release,runtime,revenue_usd_adj,budget_usd_adj,surplus,ratio_adj,roi,is_first_released_in_cinemas,is_first_released_in_cinemas_safe,release_category,ageCert
1340,398978,tt1302006,2019,11,2019-11-01,4,The Irishman,False,False,-1.0,209,1.154717e+06,1.895024e+08,-1.889251e+08,0.006093,-0.996953,False,False,Not released in major markets,U
2324,255839,tt0077749,1978,2,1978-02-28,1,The Irishman,True,True,26240.0,108,3.303580e+06,4.461426e+06,-2.809636e+06,0.740476,-0.629762,True,True,Far streaming release,U

In [17]:
filtered_data = movie

In [18]:
fig = px.scatter(
    filtered_data,
    x="budget_usd_adj",
    y="revenue_usd_adj",
    color="release_category",
    labels={
        "budget_usd_adj": "Adjusted Budget (USD)",
        "revenue_usd_adj": "Adjusted Revenue (USD)",
    },
    title="Scatter Plot of Revenue vs Budget by Release Category",
    log_x=True,
    log_y=True,
    color_discrete_sequence=px.colors.qualitative.Pastel,
)

fig.update_layout(
    xaxis_title="Adjusted Budget (USD)",
    yaxis_title="Adjusted Revenue (USD)",
    legend_title="Release Category",
    xaxis_tickangle=-45,
    xaxis_tickfont_size=12,
    yaxis_tickfont_size=12,
)

fig.show()

In [19]:
fig = px.box(
    filtered_data,
    x="release_category",
    y="roi",
    title="Boxplot of ROI by Release Category (Log Scale)",
    labels={"roi": "ROI", "release_category": "Release Category"},
    log_y=True,
    color="release_category",
    color_discrete_map={
        "Streaming release": "rgba(204, 80, 62, 1)",
        "Not released in major markets": "rgba(237, 172, 8, 1)",
        "Far streaming release": "rgba(115, 175, 72, 1)",
        "Close streaming release": "rgba(95, 70, 144, 1)",
    },
)

fig.update_layout(
    plot_bgcolor="white",
    paper_bgcolor="white",
    yaxis=dict(gridcolor="lightgray", zerolinecolor="lightgray"),
    xaxis=dict(gridcolor="lightgray", zerolinecolor="lightgray"),
    font=dict(size=12),
    legend_title_text="Release Category",
)

fig.show()

# Outliers

In [20]:
# movie = movie[movie['release_category'] != 'Not released in major markets']

In [21]:
# Determining outliers for specific columns and appending the information to the dataset

# Selecting the specific columns for outlier analysis
specific_columns = ["revenue_usd_adj", "budget_usd_adj", "surplus", "ratio_adj", "roi"]

# Calculating IQR for the specific columns
Q1_specific = movie[specific_columns].quantile(0.25)
Q3_specific = movie[specific_columns].quantile(0.75)

Q1_specific_log = np.log(movie[specific_columns]).quantile(0.25)
Q3_specific_log = np.log(movie[specific_columns]).quantile(0.75)

IQR_specific = Q3_specific - Q1_specific
IQR_specific_log = Q3_specific_log - Q1_specific_log

# Creating outlier flags for each specific column
for column in specific_columns:
    lower_bound = Q1_specific[column] - 1.5 * IQR_specific[column]
    upper_bound = Q3_specific[column] + 1.5 * IQR_specific[column]
    lower_bound_log = Q1_specific_log[column] - 0.75 * IQR_specific_log[column]
    upper_bound_log = Q3_specific_log[column] + 0.75 * IQR_specific_log[column]
    movie[f"{column}_outlier"] = (movie[column] < lower_bound) | (
        movie[column] > upper_bound
    )
    movie[f"{column}_outlier_log"] = (np.log(movie[column]) < lower_bound_log) | (
        np.log(movie[column]) > upper_bound_log
    )

In [22]:
# showing the outliers
outliers = movie[movie["roi_outlier"]]

In [23]:
movie

,movie_id,imdb_id,year,month,release_date,quarter,original_title,is_released__scope,is_released__US,days_from_us_release,...,revenue_usd_adj_outlier,revenue_usd_adj_outlier_log,budget_usd_adj_outlier,budget_usd_adj_outlier_log,surplus_outlier,surplus_outlier_log,ratio_adj_outlier,ratio_adj_outlier_log,roi_outlier,roi_outlier_log
0,8681,tt0936501,2008,2,2008-02-18,1,Taken,True,True,-65.0,...,True,False,False,False,True,False,True,False,True,False
1,24684,tt1174732,2009,10,2009-10-29,4,An Education,True,True,120.0,...,False,False,False,False,False,False,False,False,False,False
2,95023,tt0087300,1986,2,1986-02-21,1,The Frog Prince,True,True,23325.0,...,False,True,False,False,False,False,False,True,False,False
3,24685,tt0380798,2004,10,2004-10-06,4,Vipère au poing,True,False,-1.0,...,False,False,False,False,False,False,False,False,False,False
4,8688,tt0120832,1998,8,1998-08-07,3,Snake Eyes,True,True,8236.0,...,True,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12126,24682,tt0857177,2007,11,2007-11-15,4,O Magnata,True,True,15388.0,...,False,False,False,False,False,False,False,False,False,False
12127,132363,tt1327773,2013,8,2013-08-16,3,The Butler,True,True,183.0,...,True,False,False,False,True,False,True,False,True,False
12128,245703,tt2649554,2016,2,2016-02-18,1,Midnight Special,True,False,-1.0,...,False,False,False,False,False,False,False,False,False,False
12129,8675,tt0124819,1998,7,1998-07-02,3,Orgazmo,True,False,-1.0,...,False,False,False,False,False,False,False,False,False,False
12130,8676,tt0770752,2008,2,2008-02-07,1,Fool's Gold,True,True,113.0,...,True,False,True,False,False,False,False,False,False,False

In [24]:
outlier_features = [
    "revenue_usd_adj_outlier",
    "revenue_usd_adj_outlier_log",
    "budget_usd_adj_outlier",
    "budget_usd_adj_outlier_log",
    "surplus_outlier",
    "surplus_outlier_log",
    "ratio_adj_outlier",
    "ratio_adj_outlier_log",
    "roi_outlier",
    "roi_outlier_log",
]
# Create subplots
fig = make_subplots(rows=5, cols=2, subplot_titles=outlier_features)

# Adding scatter plots to the respective subplot
for i, feature in enumerate(outlier_features):
    row = i // 2 + 1
    col = i % 2 + 1
    filtered_data = movie[movie[feature]]  # Filter data for outliers
    fig.add_trace(
        go.Scattergl(
            x=filtered_data["budget_usd_adj"],
            y=filtered_data["revenue_usd_adj"],
            mode="markers",
            name=feature,
            marker=dict(size=7, opacity=0.7),
        ),
        row=row,
        col=col,
    )

# Update axes and layout
fig.update_xaxes(type="log", title_text="Budget (USD)")
fig.update_yaxes(type="log", title_text="Revenue (USD)")
fig.update_layout(
    height=1500,
    width=1000,
    title_text="Scatter plots for Outliers by Category",
    showlegend=False,
)

# Show plot
fig.show()

In [25]:
outlier_features = [
    "revenue_usd_adj_outlier",
    "revenue_usd_adj_outlier_log",
    "budget_usd_adj_outlier",
    "budget_usd_adj_outlier_log",
    "surplus_outlier",
    "surplus_outlier_log",
    "ratio_adj_outlier",
    "ratio_adj_outlier_log",
    "roi_outlier",
    "roi_outlier_log",
]

# Create a 5x2 subplot grid
fig = make_subplots(rows=5, cols=2, subplot_titles=outlier_features)

# Populate the subplots with scatter plots
for index, feature in enumerate(outlier_features):
    row = (index // 2) + 1
    col = (index % 2) + 1
    # Filter data for the current feature
    current_data = movie[movie[feature]]

    # Add a scatter plot to the current subplot
    fig.add_trace(
        go.Scattergl(
            x=current_data["budget_usd_adj"],
            y=current_data["revenue_usd_adj"],
            mode="markers",
            marker=dict(size=7, opacity=0.7),
            name=f"Outliers in {feature}",  # Legend name
        ),
        row=row,
        col=col,
    )

    # Print number of outliers in the console/log
    print(f"Number of outliers in {feature}: ", len(current_data))

# Update layout for better appearance and readability
fig.update_layout(
    height=1500,
    width=1200,
    title_text="Scatter plots of Various Outlier Features",
    showlegend=True,
)
fig.update_xaxes(title_text="Budget (USD, log scale)", type="log")
fig.update_yaxes(title_text="Revenue (USD, log scale)", type="log")

# Show the figure
fig.show()

Number of outliers in revenue_usd_adj_outlier:  1510
Number of outliers in revenue_usd_adj_outlier_log:  1283
Number of outliers in budget_usd_adj_outlier:  1027
Number of outliers in budget_usd_adj_outlier_log:  1181
Number of outliers in surplus_outlier:  2306
Number of outliers in surplus_outlier_log:  367
Number of outliers in ratio_adj_outlier:  1140
Number of outliers in ratio_adj_outlier_log:  1693
Number of outliers in roi_outlier:  1140
Number of outliers in roi_outlier_log:  579

In [26]:
movie[(movie["release_category"] == "Far streaming release")][
    ["revenue_usd_adj", "budget_usd_adj", "surplus", "ratio_adj", "roi"]
].describe().drop("count").style.format(
    {
        "revenue_usd_adj": "${:,.0f}",
        "budget_usd_adj": "${:,.0f}",
        "surplus": "${:,.0f}",
        "ratio_adj": "{:.2f}",
        "roi": "{:.2f}",
    }
)

In [27]:
movie[(movie["release_category"] != "Far streaming release")][
    ["revenue_usd_adj", "budget_usd_adj", "surplus", "ratio_adj", "roi"]
].describe().drop("count").style.format(
    {
        "revenue_usd_adj": "${:,.0f}",
        "budget_usd_adj": "${:,.0f}",
        "surplus": "${:,.0f}",
        "ratio_adj": "{:.2f}",
        "roi": "{:.2f}",
    }
)

In [28]:
movie_no_out = movie[(movie["release_category"] == "Far streaming release")]

fig = px.scatter(
    movie_no_out,
    x="budget_usd_adj",
    y="revenue_usd_adj",
    labels={
        "budget_usd_adj": "Adjusted Budget (USD)",
        "revenue_usd_adj": "Adjusted Revenue (USD)",
    },
    title="Scatter Plot of Revenue vs Budget for Movies within Scope with Far Streaming Release",
    hover_name="original_title",
    log_x=True,
    log_y=True,
)

fig.update_layout(
    xaxis_title="Adjusted Budget (USD)",
    yaxis_title="Adjusted Revenue (USD)",
    xaxis_tickangle=-45,
    xaxis_tickfont_size=12,
    yaxis_tickfont_size=12,
    height=800,
    width=800,
)

fig.show()

In [29]:
print("Smallest ratio movies")
display(
    movie_no_out.sort_values(by="ratio_adj")
    .head(10)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.5f}",
        }
    )
)

print("Biggest ratio movies")
display(
    movie_no_out.sort_values(by="ratio_adj", ascending=False)
    .head(10)[
        [
            "movie_id",
            "original_title",
            "revenue_usd_adj",
            "budget_usd_adj",
            "surplus",
            "ratio_adj",
            "roi",
        ]
    ]
    .style.format(
        {
            "revenue_usd_adj": "${:,.0f}",
            "budget_usd_adj": "${:,.0f}",
            "surplus": "${:,.0f}",
            "ratio_adj": "{:.2f}",
            "roi": "{:.2f}",
        }
    )
)

Smallest ratio movies

Biggest ratio movies

# Genres

In [30]:
# Join the movie and the genre table
movie_genre = movie.merge(genres, how="left", on="movie_id")

In [31]:
# Can you give some basic statistics per genre for the ratio and the ROI?
print("Basic statistics per genre for the ratio and the ROI: ")
display(
    movie_genre.groupby("name")[["ratio_adj", "roi"]].describe().style.format("{:,.2f}")
)

Basic statistics per genre for the ratio and the ROI:

In [32]:
# Can you give some basic statistics per genre for the ratio and the ROI?
print("Basic statistics per US theatrical release for the ratio and the ROI: ")
display(
    movie_genre.groupby("name")[["ratio_adj", "roi"]].describe().style.format("{:,.2f}")
)

Basic statistics per US theatrical release for the ratio and the ROI:

# Production Companies

In [33]:
# Join the movie and the production companies table
movie_production_companies = movie.merge(
    production_companies, how="left", on="movie_id"
)

In [34]:
# Number of production companies
print(
    "Number of production companies: ",
    len(movie_production_companies["company_name"].unique()),
)
# # Number of parent companies (companies that own other companies)
# print('Number of parent companies: ', len(movie_production_companies['parent_name'].unique()))

Number of production companies:  11717

In [35]:
# Number of production companies per movie
print(
    "Number of production companies per movie: {0:.2f}".format(
        movie_production_companies.groupby("movie_id")["company_name"].count().mean()
    )
)

Number of production companies per movie: 3.09

In [36]:
# Biggest production companies (by number of movies and by revenue)
biggest_companies = movie_production_companies.groupby("company_name").agg(
    {"movie_id": "count", "revenue_usd_adj": "sum"}
)
biggest_companies.columns = ["Number of Movies", "Total Revenue"]
biggest_companies = biggest_companies.sort_values(
    by="Number of Movies", ascending=False
).head(10)
display(biggest_companies)

                      Number of Movies  Total Revenue
company_name
warner_bros_pictures               641   1.179585e+11
universal_pictures                 618   1.081712e+11
columbia_pictures                  496   8.101153e+10
paramount_pictures                 472   9.352475e+10
20th_century_fox                   466   9.195368e+10
canal_                             338   9.805494e+09
new_line_cinema                    254   3.938654e+10
metro_goldwyn_mayer                238   2.601777e+10
france_2_cinema                    222   3.403914e+09
touchstone_pictures                194   2.624422e+10

In [37]:
# # Biggest parent production companies (by number of movies and by revenue)
# biggest_parent_companies = movie_production_companies.groupby('parent_name').agg({'movie_id': 'count', 'revenue_usd_adj': 'sum'})
# biggest_parent_companies.columns = ['Number of Movies', 'Total Revenue']
# biggest_parent_companies = biggest_parent_companies.sort_values(by='Number of Movies', ascending=False).head(10).format({
#     'Total Revenue': "${:,.0f}"
# })
# display(biggest_parent_companies)

In [38]:
# # Companies with the most subsidiaries
# subsidiaries = movie_production_companies.groupby('parent_name').agg({'company_name': 'nunique'})
# subsidiaries.columns = ['Number of Subsidiaries']
# subsidiaries = subsidiaries.sort_values(by='Number of Subsidiaries', ascending=False).head(10)
# display(subsidiaries)

# Keywords

In [39]:
movie_keywords = movie.merge(keywords, how="left", on="movie_id")

In [40]:
print("Number of keywords: ", len(movie_keywords["keyword_name"].unique()))

Number of keywords:  15734

In [41]:
# On average, how many keywords are there per movie?
print(
    "Average number of keywords per movie: ",
    movie_keywords.groupby("movie_id")["keyword_name"].count().mean(),
)

Average number of keywords per movie:  7.5976424037589645

In [42]:
# The most popular keywords (by number of movies and by revenue)
popular_keywords = movie_keywords.groupby("keyword_name").agg(
    {"movie_id": "count", "revenue_usd_adj": "sum"}
)
popular_keywords.columns = ["Number of Movies", "Total Revenue"]
popular_keywords = (
    popular_keywords.sort_values(by="Number of Movies", ascending=False)
    .head(10)
    .style.format({"Total Revenue": "${:,.0f}"})
)
display(popular_keywords)

# Time analysis

In [43]:
plot_and_export_categorical_distribution(movie, "runtime", "runtime", 0, False, True, "charts", True, True, filename_prefix='step_2')

    grouped  total
0        71      1
1        73      5
2        74      5
3        75     10
4        76     14
..      ...    ...
137     234      1
138     242      1
139     254      1
140     285      1
141     360      1

[142 rows x 2 columns]

In [44]:
plot_and_export_categorical_distribution(movie, "year", "year", 0, False, True, "charts", True, True, filename_prefix='step_2')

   grouped  total
0     1970      9
1     1971     50
2     1972     48
3     1973     58
4     1974     59
5     1975     74
6     1976     69
7     1977     70
8     1978     96
9     1979     99
10    1980    107
11    1981    135
12    1982    130
13    1983    121
14    1984    136
15    1985    156
16    1986    170
17    1987    196
18    1988    200
19    1989    175
20    1990    163
21    1991    177
22    1992    179
23    1993    192
24    1994    185
25    1995    211
26    1996    220
27    1997    243
28    1998    226
29    1999    263
30    2000    264
31    2001    280
32    2002    326
33    2003    320
34    2004    333
35    2005    375
36    2006    417
37    2007    456
38    2008    442
39    2009    447
40    2010    452
41    2011    477
42    2012    423
43    2013    482
44    2014    459
45    2015    473
46    2016    466
47    2017    407
48    2018    344
49    2019    271

In [45]:
plot_and_export_categorical_distribution(movie, "quarter", "quarter", 0, False, True, "charts", True, True, filename_prefix='step_2')

  grouped  total
0       1   2599
1       2   2764
2       3   3356
3       4   3412

In [46]:
plot_and_export_categorical_distribution(movie, "month", "month", 0, False, True, "charts", True, True, filename_prefix='step_2')

   grouped  total
0        1    778
1        2    828
2        3    993
3        4    929
4        5    913
5        6    922
6        7    811
7        8   1075
8        9   1470
9       10   1272
10      11    957
11      12   1183

In [47]:
plot_and_export_categorical_distribution(movie, "release_category", "release_category", 0, False, True, "charts", True, True, filename_prefix='step_2')

                         grouped  total
0        Close streaming release    256
1          Far streaming release   7977
2  Not released in major markets   1813
3              Streaming release   2085

In [48]:
plot_and_export_categorical_distribution(movie, "ageCert", "ageCert", 0, False, True, "charts", True, True, filename_prefix='step_2')

  grouped  total
0       G     99
1      NR    199
2      PG   1233
3    PG13   2150
4       R   3631
5       U   4819