# Set up

In [1]:
import pandas as pd
from IPython.display import display

from eda_support_functions import *

# Suppress all warnings
import warnings

warnings.filterwarnings("ignore")

In [2]:
full__regression__none = pd.read_csv(
    "../data/ml_ready_data/full__regression__with_outliers__none.csv"
)

In [3]:
full__regression__complex = pd.read_csv(
    "../data/ml_ready_data/full__regression__with_outliers__complex.csv"
)

In [4]:
full__regression__complex.shape

(12131, 387)

In [5]:
full__regression__complex = full__regression__complex.convert_dtypes(infer_objects=True)

In [6]:
# Make a dataframe with the columns that we have in the full__regression__complex dataframe, and then a column with the splits ("__") in the column names
full__regression__complex_columns = pd.DataFrame(
    full__regression__complex.columns, columns=["column_name"]
)
full__regression__complex_columns["level_1"] = full__regression__complex_columns[
    "column_name"
].apply(lambda x: x.split("__")[0])
full__regression__complex_columns["level_2"] = full__regression__complex_columns[
    "column_name"
].apply(lambda x: x.split("__")[1] if len(x.split("__")) > 1 else None)

In [7]:
full__regression__complex_columns["boolean_true"] = full__regression__complex_columns[
    "column_name"
].apply(
    lambda x: full__regression__complex[x].sum()
    if full__regression__complex[x].dtype == "boolean"
    else None
)

In [8]:
a = full__regression__complex_columns[
    full__regression__complex_columns["boolean_true"].notnull()
].sort_values("boolean_true", ascending=False)
a["normalized"] = a["boolean_true"] / full__regression__complex.shape[0]

In [9]:
a

,column_name,level_1,level_2,boolean_true,normalized
310,is_spoken_language__en,is_spoken_language,en,9081.0,0.748578
7,is_released__US,is_released,US,8474.0,0.698541
373,is_prod_country__US,is_prod_country,US,7382.0,0.608524
58,is_genre__Drama,is_genre,Drama,6440.0,0.530871
9,is_released__FR,is_released,FR,6370.0,0.525101
...,...,...,...,...,...
260,is_collection__los_superagentes,is_collection,los_superagentes,0.0,0.000000
259,is_collection__lone_wolf_and_cub_collection,is_collection,lone_wolf_and_cub_collection,0.0,0.000000
258,is_collection__les_charlots_saga,is_collection,les_charlots_saga,0.0,0.000000
256,is_collection__lemon_popsicle,is_collection,lemon_popsicle,0.0,0.000000
215,is_collection__basnici_kolekcia_,is_collection,basnici_kolekcia_,0.0,0.000000

In [10]:
a.groupby("level_1").agg({"normalized": ["mean", "min", "max"]}).rename(
    columns={"normalized": ""}
)

                          mean       min       max
level_1
is_collection         0.000191  0.000000  0.001484
is_genre              0.124271  0.000659  0.530871
is_keyword            0.019280  0.001566  0.077735
is_on_holiday_window  0.403594  0.403594  0.403594
is_outlier            0.456351  0.456351  0.456351
is_prod_company       0.007702  0.000000  0.052840
is_prod_country       0.032728  0.000495  0.608524
is_released           0.391180  0.037755  0.698541
is_spoken_language    0.047109  0.001896  0.748578

In [11]:
full__regression__complex_columns.groupby("level_1").agg(
    {"level_2": "count", "boolean_true": "sum"}
).sort_values("level_2", ascending=False)

                                    level_2  boolean_true
level_1
is_collection                            91         211.0
is_prod_company                          89        8316.0
is_keyword                               53       12396.0
is_prod_country                          42       16675.0
is_spoken_language                       29       16573.0
is_genre                                 19       28643.0
is_released                               5       23727.0
actor_kpis                                4           0.0
producer_kpis                             4           0.0
genre_kpis                                4           0.0
keyword_kpis                              4           0.0
director_kpis                             4           0.0
production_company_kpis                   4           0.0
composer_kpis                             4           0.0
collection_kpis                           4           0.0
writer_kpis                               4           0.0
month_cos                                 0           0.0
movies_released_within_15_days            0           0.0
production_size                           0           0.0
quarter                                   0           0.0
revenue_usd_adj                           0           0.0
movie_id                                  0           0.0
month_sin                                 0           0.0
runtime                                   0           0.0
original_language                         0           0.0
is_outlier                                0        5536.0
month                                     0           0.0
ageCert                                   0           0.0
is_on_holiday_window                      0        4896.0
gdp_growth_oecd                           0           0.0
empl_rate_oecd                            0           0.0
economic_situation_oecd                   0           0.0
days_to_xmas                              0           0.0
days_to_thanksgiving                      0           0.0
days_to_labour_day                        0           0.0
consumer_prices_oecd                      0           0.0
composite_consumer_confidence_oecd        0           0.0
budget_usd_adj                            0           0.0
year                                      0           0.0

In [12]:
full__regression__none

,movie_id,original_language,runtime,ageCert,quarter,month,year,is_released__US,is_released__CN,is_released__FR,is_released__GB,is_released__JP,budget_usd_adj,revenue_usd_adj,is_outlier,production_size
0,8681,en,94,PG13,1,2,2008,True,False,True,True,True,3.538060e+07,3.210161e+08,True,large_productions
1,24684,en,100,PG13,4,10,2009,True,False,True,True,False,1.065208e+07,3.706476e+07,False,small_productions
2,95023,en,100,PG,1,2,1986,True,False,False,False,False,3.613279e+06,2.780128e+00,True,small_productions
3,24685,fr,100,U,4,10,2004,False,False,True,False,False,1.340625e+07,1.144569e+07,True,medium_productions
4,8688,en,98,R,3,8,1998,True,False,True,True,True,1.364616e+08,1.942081e+08,False,large_productions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12126,24682,pt,93,U,4,11,2007,True,False,False,False,False,4.188253e+06,9.419248e+05,False,small_productions
12127,132363,en,132,PG13,3,8,2013,True,False,True,True,False,3.269938e+07,2.319221e+08,False,large_productions
12128,245703,en,112,U,1,2,2016,False,False,True,True,False,2.285198e+07,9.029431e+06,True,medium_productions
12129,8675,en,94,U,3,7,1998,False,False,False,True,False,1.869337e+06,1.125906e+06,True,small_productions
12130,8676,en,112,PG13,1,2,2008,True,False,True,True,False,9.906569e+07,1.574169e+08,False,large_productions

In [13]:
full__regression__none.shape

(12131, 16)

In [14]:
(
    full__regression__none.groupby(["is_outlier", "production_size"])
    .size()
    .unstack(fill_value=0)
    .rename(index={False: "Not Outlier", True: "Outlier"})
    .assign(Total=lambda x: x.sum(axis=1))
    .pipe(
        lambda df: pd.concat([df, pd.DataFrame([df.sum()], index=["Total"])])
        .fillna(0)
        .astype(int)
    )
    .style
    #  .background_gradient(cmap='YlOrRd')
    .format("{:,d}")
)

In [15]:
full__regression__none["ratio"] = (
    full__regression__none["budget_usd_adj"] / full__regression__none["revenue_usd_adj"]
)

In [16]:
display(
    full__regression__none[~full__regression__none["is_outlier"]]
    .sort_values(by="ratio", ascending=False)[
        [
            "movie_id",
            "original_language",
            "year",
            "ratio",
            "budget_usd_adj",
            "revenue_usd_adj",
        ]
    ]
    .head(30)
    .style.format({"budget_usd_adj": "${:,.0f}", "revenue_usd_adj": "${:,.0f}"})
)

In [17]:
display(
    full__regression__none[~full__regression__none["is_outlier"]]
    .sort_values(by="ratio", ascending=True)[
        ["movie_id", "ratio", "budget_usd_adj", "revenue_usd_adj"]
    ]
    .head(10)
    .style.format({"budget_usd_adj": "${:,.0f}", "revenue_usd_adj": "${:,.0f}"})
)